language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8


script:
  - ./gradlew clean test
  - jdk_switcher use openjdk6
  - ./gradlew clean integTest

before_install:
  - chmod +x gradlew

after_success:
- "./gradlew jacocoTestReport coveralls --debug"
- "./gradlew publishPlugins"